// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwBtezeTbz1g3neqU5joFRQDWYbfkXnc',
    appId: '1:1007662809502:web:35d9ef1f1a07ee3996568f',
    messagingSenderId: '1007662809502',
    projectId: 'travelminds-c6dbf',
    authDomain: 'travelminds-c6dbf.firebaseapp.com',
    storageBucket: 'travelminds-c6dbf.firebasestorage.app',
    measurementId: 'G-3D35NW6YLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lB0eZtEAVNcCNpdfWIKCKGawZZZLrjQ',
    appId: '1:1007662809502:android:bcf03c1b0896314b96568f',
    messagingSenderId: '1007662809502',
    projectId: 'travelminds-c6dbf',
    storageBucket: 'travelminds-c6dbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Z-AmnLDRs0Ry_EqgBJc9IlxLJY7i3eQ',
    appId: '1:1007662809502:ios:4006249bd46fa5e396568f',
    messagingSenderId: '1007662809502',
    projectId: 'travelminds-c6dbf',
    storageBucket: 'travelminds-c6dbf.firebasestorage.app',
    iosBundleId: 'com.example.travelMinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Z-AmnLDRs0Ry_EqgBJc9IlxLJY7i3eQ',
    appId: '1:1007662809502:ios:4006249bd46fa5e396568f',
    messagingSenderId: '1007662809502',
    projectId: 'travelminds-c6dbf',
    storageBucket: 'travelminds-c6dbf.firebasestorage.app',
    iosBundleId: 'com.example.travelMinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdwBtezeTbz1g3neqU5joFRQDWYbfkXnc',
    appId: '1:1007662809502:web:0555c526aa155a6696568f',
    messagingSenderId: '1007662809502',
    projectId: 'travelminds-c6dbf',
    authDomain: 'travelminds-c6dbf.firebaseapp.com',
    storageBucket: 'travelminds-c6dbf.firebasestorage.app',
    measurementId: 'G-HX4CQLSHE8',
  );
}
